/* DO NOT EDIT THIS FILE - it is machine generated */

#include <jni.h>


#ifndef _Included_com_machfe_easypr_exportjni
#define _Included_com_machfe_easypr_exportjni
#ifdef __cplusplus
extern "C" {
#endif

    
JNIEXPORT void JNICALL Java_com_machfe_easypr_EasyPRLib_init
    (JNIEnv*  env, jobject  obj, jstring path);
    
    
JNIEXPORT jobjectArray JNICALL Java_com_machfe_easypr_EasyPRLib_Recognize
    ( JNIEnv*  env, jobject  obj, jstring path);




#ifdef __cplusplus
}
#endif
#endif